#!/usr/bin/env bash
# Generate docs/profile-keys.md from templates/profile.schema.json.
#
# The reference is generated rather than written because this repository has been bitten by profile
# drift twice, and a hand-written copy of 55 keys is a second thing to keep in step with the first.
# Generated, a stale page is a failing build rather than a wrong sentence.
#
# The "Set by" column comes from running `keel init` in a throwaway fixture rather than from a list
# maintained here. That list would drift the same way: it said twelve human-only keys until the
# context window work moved one of them, and nothing would have noticed.
#
# Deterministic by construction: no date, no path, no counter, nothing from the environment.
#
# Usage: tests/generate-profile-keys.sh > docs/profile-keys.md   (from the repository root)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# One init, about a second. The key set it writes is the same for every stack, checked against
# empty, node and go fixtures on 2026-08-18, so an empty fixture is enough and is the least
# arbitrary choice.
( cd "$work" && git init -q -b main . && "$ROOT/bin/keel" init -y >/dev/null 2>&1 )

SCHEMA="$ROOT/templates/profile.schema.json" PROFILE="$work/.keel/profile.json" python3 - <<'PY'
import json, os

schema = json.load(open(os.environ["SCHEMA"]))


def type_of(v):
    """What a reader needs to know they may put here.

    Eleven keys constrain by `enum` and carry no `type`. For those the allowed values are the
    useful answer: "one of: required, warn, off" tells a reader what to write, where "string"
    does not.
    """
    if v.get("enum"):
        return "one of: " + ", ".join("`%s`" % e for e in v["enum"])
    t = v.get("type", "")
    return (t if isinstance(t, str) else "/".join(t)) or "unconstrained"


def read_by(v):
    """What reads this key, as the reference page shows it.

    A person reading the page needs one of four answers: something reads it, a person reads it,
    nothing reads it, or nothing is written to and a model was measured reading it anyway. The citation is printed rather than summarised because the citation is
    the thing tests/validate-skills.sh checks, and a summary would be a second copy to keep in
    step with it.
    """
    e = v.get("x-keel-read-by")
    if e is None:
        return "_undeclared_"
    if isinstance(e, str):
        e = [e]
    out = []
    for one in e:
        if one == "human":
            out.append("a person")
        elif one.startswith("unread:"):
            out.append("nothing yet, see `%s`" % one.split(":", 1)[1])
        elif one.startswith("observed:"):
            out.append("a model, unprompted, see `%s`" % one.split(":", 1)[1])
        elif one.startswith("advisory:"):
            out.append("`%s` (advisory)" % one.split(":", 1)[1])
        elif one.startswith("generic:"):
            out.append("`%s` (generic)" % one.split(":", 1)[1])
        else:
            out.append("`%s`" % one.split(":", 1)[1])
    return ", ".join(out)


def declared(node, p=""):
    out = []
    for k, v in (node.get("properties") or {}).items():
        path = "%s.%s" % (p, k) if p else k
        if isinstance(v, dict) and v.get("properties"):
            out += declared(v, path)
        else:
            out.append((path, type_of(v), read_by(v), (v.get("description") or "").strip()))
    return out


def leaves(o, p=""):
    s = set()
    if isinstance(o, dict):
        for k, v in o.items():
            s |= leaves(v, "%s.%s" % (p, k) if p else k)
    else:
        s.add(p)
    return s


written = leaves(json.load(open(os.environ["PROFILE"])))

print("# Profile keys")
print()
print("Every key `.keel/profile.json` may contain, what it does, whether keel writes it, and what")
print("reads it back.")
print()
print("Generated by `tests/generate-profile-keys.sh` from `templates/profile.schema.json`.")
print("Do not edit by hand: `tests/validate-skills.sh` fails when this file and the schema")
print("disagree, and names the command that regenerates it.")
print()
print("**Set by** is derived by running `keel init` against a throwaway fixture, so it cannot")
print("drift from what init actually writes. A key marked **you** is one keel never writes: it")
print("does nothing until a human adds it.")
print()
print("**Read by** comes from each key's `x-keel-read-by` in the schema, and")
print("`tests/validate-skills.sh` fails when the citation it gives no longer points at a real,")
print("non-blank line. A file and line means something there reads the value; \"(advisory)\" marks")
print("prose a model may follow rather than code that executes; \"a person\" means the key exists to")
print("be read by a human or quoted into a runbook; \"nothing yet\" means nothing reads it and names")
print("the record that decided so. The check proves the citation resolves, not that it matches the")
print("key: 20 of 61 keys were read by nothing on 2026-09-07 while the changelog recorded seven.")
print()
print("| Key | Type | Set by | Read by | Description |")
print("|---|---|---|---|---|")
# Five rows name a gate, so this page makes a harness claim and
# tests/test-harness-claims.sh scans it. The tag goes HERE rather than into docs/profile-keys.md,
# because that file is generated: a tag written into the output is wiped by the next regeneration
# with nothing going red. It rides in the row rather than on a line above it, because an HTML
# comment on its own line between two table rows ends the table in GitHub-flavoured markdown, and
# the scan skips any line carrying its own tag.
#
# done_verified drives done-guard, which is active on both harnesses. hard_block_paths is enforced
# by sensitive-guard, which needs a hook that can put a command to a human, and Codex offers none.
# Claiming it for codex is what lib/harness/capabilities would refuse.
#
# The last three are named by their Read by cell rather than by their description, which is why they
# were not needed before this column existed: the column prints a citation, so those rows name
# hooks/session-start and hooks/done-guard in a cell nobody wrote by hand. Both gates are active on
# both harnesses, which tests/test-harness-resolve.sh pins, so both tags are granted. Deleting any
# of the three turns tests/test-harness-claims.sh red, which is how to tell these tags are load
# bearing rather than decoration. If a tag is ever refused, the manifest is the authority and the
# citation is what changes, not the tag.
CLAIMS = {
    "gates.done_verified": ["gate=done-guard harness=claude", "gate=done-guard harness=codex"],
    "hard_block_paths": ["gate=sensitive-guard harness=claude"],
    "conventions.response_style": ["gate=session-start harness=claude", "gate=session-start harness=codex"],
    "conventions.explain_level": ["gate=session-start harness=claude", "gate=session-start harness=codex"],
    "verify.test": ["gate=done-guard harness=claude", "gate=done-guard harness=codex"],
}

for path, typ, rb, desc in declared(schema):
    setby = "`keel init`" if path in written else "**you**"
    text = (desc or "_No description yet._").replace("|", "\\|")
    tags = "".join(" <!-- keel:claim %s -->" % c for c in CLAIMS.get(path, []))
    print("| `%s` | %s | %s | %s | %s%s |" % (path, typ, setby, rb, text, tags))
PY
