#!/usr/bin/env bash
# Generate docs/profile-keys.md from templates/profile.schema.json.
#
# The reference is generated rather than written because this repository has been bitten by profile
# drift twice, and a hand-written copy of 59 keys is a second thing to keep in step with the first.
# Generated, a stale page is a failing build rather than a wrong sentence.
#
# The "Set by" column comes from running `keel init` in a throwaway fixture rather than from a list
# maintained here. That list would drift the same way: it said twelve human-only keys until the
# context window work moved one of them, and nothing would have noticed.
#
# Deterministic by construction: no date, no path, no counter, nothing from the environment.
#
# Usage: tests/generate-profile-keys.sh > docs/profile-keys.md   (from the repository root)
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# One init, about a second. The key set it writes is the same for every stack, checked against
# empty, node and go fixtures on 2026-08-18, so an empty fixture is enough and is the least
# arbitrary choice.
( cd "$work" && git init -q -b main . && "$ROOT/bin/keel" init -y >/dev/null 2>&1 )

SCHEMA="$ROOT/templates/profile.schema.json" PROFILE="$work/.keel/profile.json" python3 - <<'PY'
import json, os

schema = json.load(open(os.environ["SCHEMA"]))


def type_of(v):
    """What a reader needs to know they may put here.

    Eleven keys constrain by `enum` and carry no `type`. For those the allowed values are the
    useful answer: "one of: required, warn, off" tells a reader what to write, where "string"
    does not.
    """
    if v.get("enum"):
        return "one of: " + ", ".join("`%s`" % e for e in v["enum"])
    t = v.get("type", "")
    return (t if isinstance(t, str) else "/".join(t)) or "unconstrained"


def declared(node, p=""):
    out = []
    for k, v in (node.get("properties") or {}).items():
        path = "%s.%s" % (p, k) if p else k
        if isinstance(v, dict) and v.get("properties"):
            out += declared(v, path)
        else:
            out.append((path, type_of(v), (v.get("description") or "").strip()))
    return out


def leaves(o, p=""):
    s = set()
    if isinstance(o, dict):
        for k, v in o.items():
            s |= leaves(v, "%s.%s" % (p, k) if p else k)
    else:
        s.add(p)
    return s


written = leaves(json.load(open(os.environ["PROFILE"])))

print("# Profile keys")
print()
print("Every key `.keel/profile.json` may contain, what it does, and whether keel writes it.")
print()
print("Generated by `tests/generate-profile-keys.sh` from `templates/profile.schema.json`.")
print("Do not edit by hand: `tests/validate-skills.sh` fails when this file and the schema")
print("disagree, and names the command that regenerates it.")
print()
print("**Set by** is derived by running `keel init` against a throwaway fixture, so it cannot")
print("drift from what init actually writes. A key marked **you** is one keel never writes: it")
print("does nothing until a human adds it.")
print()
print("| Key | Type | Set by | Description |")
print("|---|---|---|---|")
for path, typ, desc in declared(schema):
    setby = "`keel init`" if path in written else "**you**"
    text = (desc or "_No description yet._").replace("|", "\\|")
    print("| `%s` | %s | %s | %s |" % (path, typ, setby, text))
PY
