#!/usr/bin/env bash
# Generate a harness's hook manifest from lib/harness/capabilities.
#
# Generated rather than written because four things have to agree about which gates a harness gets,
# and a hand-maintained copy is the fourth one that goes stale. A stale file is a failing build here,
# the same bargain tests/generate-profile-keys.sh makes for docs/profile-keys.md.
#
# THE CLAUDE CODE MANIFEST IS THE SPECIFICATION, not an output to be inspected. hooks/hooks.json is
# committed and installed today, and R-01 says no Claude Code behaviour changes, so
# tests/test-harness-resolve.sh diffs this generator's output against that file byte for byte.
# Valid JSON that is not that file is a failure, not a formatting preference.
#
# Deterministic by construction: no date, no path, no counter, nothing from the environment.
#
# Usage: tests/generate-harness-artifacts.sh claude > hooks/hooks.json
#        tests/generate-harness-artifacts.sh codex  > hooks/hooks.codex.json
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
# shellcheck source-path=SCRIPTDIR/..
# shellcheck source=lib/harness/resolve.sh
. "$ROOT/lib/harness/resolve.sh"

CAP="$ROOT/lib/harness/capabilities"

# ---- the support page ------------------------------------------------------
#
# Generated for the same reason the hook manifests are: it is the page a reader is sent to when they
# ask what keel does on their harness, and a hand-maintained answer to that question is the one that
# drifts from lib/harness/capabilities without anything going red.
#
# EVERY LINE NAMING A GATE CARRIES ITS OWN CLAIM TAG, and that is not decoration. This file lands in
# docs/ at depth one, which tests/test-harness-claims.sh scans, so the page would otherwise fail the
# very check it exists to serve. The tags sit INSIDE the last cell rather than on the line above,
# which is where the plan put them: an HTML comment on its own line between two table rows ends the
# table in GitHub-flavoured markdown, and the page would render as a header, one row, and rubble.
# The scan skips any line carrying its own tag, so a tag in the row is read exactly the same way.
support_page() {
    local harnesses gates h g row

    # Harnesses in first-appearance order, gates in first-requires-row order. Manifest order rather
    # than alphabetical: the file is written to be read top to bottom, and a table that reorders it
    # makes the two disagree for no gain.
    harnesses="$(awk -F'|' '$1=="provides" {print $2}' "$CAP" | awk '!seen[$0]++')"
    gates="$(awk -F'|' '$1=="requires" {print $2}' "$CAP" | awk '!seen[$0]++')"

    printf '# Harness support\n\n'
    printf 'Generated by tests/generate-harness-artifacts.sh. Do not edit by hand.\n\n'

    printf '## Gates\n\n'
    printf '| Gate'
    for h in $harnesses; do printf ' | %s' "$h"; done
    printf ' |\n|---'
    for h in $harnesses; do printf '|---'; done
    printf '|\n'
    for g in $gates; do
        row="| $g"
        for h in $harnesses; do
            if harness_gate_active "$h" "$g"; then row="$row | yes"; else row="$row | no"; fi
        done
        for h in $harnesses; do
            harness_gate_active "$h" "$g" && row="$row <!-- keel:claim gate=$g harness=$h -->"
        done
        printf '%s |\n' "$row"
    done
    printf '\n'

    printf '## Provenance\n\n'
    printf '| Harness | Primitive | Source | Version | Checked |\n|---|---|---|---|---|\n'
    awk -F'|' '$1=="provides" {
        printf "| %s | %s | %s | %s | %s <!-- keel:claim property=%s harness=%s --> |\n", \
               $2, $3, $4, $5, $6, $3, $2
    }' "$CAP"
    printf '\n'

    # Wrapped so that both mentions of hard_block_paths land within three lines of the tag, which is
    # as far back as the scan looks. Same words as the plan gives, different line breaks.
    cat <<'PARA'
## What Tier B cannot claim

<!-- keel:claim gate=sensitive-guard harness=claude -->
Codex CLI does not provide a way for a hook to put a command to a human. keel's hard block on
`hard_block_paths` is therefore absent on Codex, not degraded, and `keel init` registers nothing for it
there. A repository that declares `hard_block_paths` and serves Codex is protected for its Claude Code
users and not for its Codex users. This page says it for every harness; `keel doctor` says it for the
one in front of you, and reports a gate its hooks are not trusted to run as dark rather than active.
PARA
}

harness="${1:-}"
[ -n "$harness" ] || { printf 'usage: %s <harness|support-page>\n' "$0" >&2; exit 1; }
if [ "$harness" = support-page ]; then support_page; exit 0; fi
harness_known "$harness" || { printf 'unknown harness: %s\n' "$harness" >&2; exit 1; }

active="$(harness_active_gates "$harness")"
is_active() { printf '%s\n' "$active" | grep -qx "$1"; }

# One entry, at the indentation hooks/hooks.json already uses. `async` is false on every entry and
# is not a parameter: a hook that cannot apply control effects is advisory, and an advisory
# sensitive-guard or done-guard is the failure this whole design exists to prevent. Codex needs a
# synchronous hook for both the exit-2 control path and the Stop decision
# (codex-rs/hooks/src/engine/mod.rs:141-156), and the suite counts entries against synchronous ones
# so that a silent flip is a red build rather than three gates quietly becoming advice.
entry() {
    local hook="$1" timeout="$2"
    cat <<ENTRY
          {
            "type": "command",
            "command": "\\"\${CLAUDE_PLUGIN_ROOT}/hooks/$hook\\"",
            "shell": "bash",
            "async": false,
            "timeout": $timeout
          }
ENTRY
}

# A matcher group, or nothing at all when the manifest withholds its gate. Printing nothing rather
# than an empty group is what lets the caller drop the whole event: sensitive-guard is inactive on
# Codex and its group simply does not exist there, with no conditional anybody has to remember.
group() {   # group <gate> <hook> <timeout> [matcher]
    is_active "$1" || return 0
    printf '      {\n'
    if [ -n "${4:-}" ]; then
        printf '        "matcher": "%s",\n' "$4"
    fi
    printf '        "hooks": [\n'
    entry "$2" "$3"
    printf '        ]\n      }'
}

# PreToolUse carries TWO matcher groups, not one, so groups are joined here rather than emitted as
# they are produced. An emitter that assumed one group per event could not reproduce
# hooks/hooks.json at all, which is why the two are separate functions.
join_groups() {
    local out="" g
    for g in "$@"; do
        [ -n "$g" ] || continue
        [ -z "$out" ] || out="$out,
"
        out="$out$g"
    done
    printf '%s' "$out"
}

# An event whose every group is inactive is DROPPED, not emitted as an empty array. hooks/hooks.json
# contains no empty array and a harness holding none of an event's gates has nothing to register
# there; emitting `"PreCompact": []` would be a claim about a gate that does not exist. Buffering
# the document is what makes that decidable, since an event's emptiness is only known after all its
# groups have run.
events=""
add_event() {   # add_event <EventName> <joined groups>
    [ -n "$2" ] || return 0
    [ -z "$events" ] || events="$events,
"
    events="$events    \"$1\": [
$2
    ]"
}

add_event SessionStart     "$(join_groups "$(group session-start   session-start   30 'startup|clear|compact')")"
add_event UserPromptSubmit "$(join_groups "$(group context-watch   context-watch   10)")"
add_event PreToolUse       "$(join_groups "$(group context-watch   context-watch   10)" \
                                          "$(group sensitive-guard sensitive-guard 10 'Bash')")"
add_event Stop             "$(join_groups "$(group done-guard      done-guard      10)")"
add_event SubagentStop     "$(join_groups "$(group done-guard      done-guard      10)")"
add_event PreCompact       "$(join_groups "$(group context-watch   context-watch   10)")"

printf '{\n  "hooks": {\n%s\n  }\n}\n' "$events"
